alias update="sudo pacman -Syu --noconfirm"
alias dotfiles="$EDITOR $DOTFILES"

alias l="exa -lA --group-directories-first --icons --git --git-repos --no-filesize --no-permissions --no-user --no-time"
alias ll="exa -lA --group-directories-first --icons --git --git-repos"

alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias c="clear"
alias q="exit"
alias d="ranger"
alias cat="bat"

alias ..="cd .."

alias mkd='mkdir -p'
alias rm='rm -rf'

alias path='echo $PATH | tr ":" "\n"'

alias installed="grep -i installed /var/log/pacman.log"

alias v="nvim"
